# Use an official Node runtime as the parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json before other files
# Utilize Docker cache to save re-installing dependencies if unchanged
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the current directory contents into the container at /app
COPY . .

# Set the host for the development server to 0.0.0.0 so it can accept connections from any IP address
ENV HOST=0.0.0.0

# Build the app
RUN npm run build

# Use a production-ready server like Nginx to serve the app
FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
