# Use an official Ruby runtime as a parent image
FROM ruby:3.0.0

# Install essential Linux packages
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client cron netcat

# Install the bundler version defined in Gemfile.lock
RUN gem install bundler:2.4.16

RUN mkdir /timebot
WORKDIR /timebot
COPY Gemfile /timebot/Gemfile
COPY Gemfile.lock /timebot/Gemfile.lock
RUN bundle install
COPY . /timebot

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]
