---
- name: Deploy Docker Compose on Database Server
  hosts: db
  become: yes
  vars:
    docker_compose_file: /root/docker-compose-db.yml

  tasks:
    - name: Copy Docker Compose file for the database
      copy:
        src: /root/docker-compose-db.yml
        dest: "{{ docker_compose_file }}"
        owner: root
        group: root
        become: yes
    
    - name: Copy .env file
      copy:
        src: /timebot-be/.env
        dest: /root/.env
        owner: root
        group: root

    - name: Run Docker Compose for the database
      command: docker-compose -f "{{ docker_compose_file }}" up -d
