---
- name: Deploy Docker Compose on Application Server
  hosts: app
  become: yes
  vars:
    docker_compose_file: /timebot-be/docker-compose-app.yml

  tasks:
    - name: Copy Docker Compose file for the application
      copy:
        src: /root/docker-compose-app.yml
        dest: "{{ docker_compose_file }}"
        owner: ec2-user
        group: ec2-user
        become: yes

    - name: Run Docker Compose for the application
      command: docker-compose -f "{{ docker_compose_file }}" up -d
