---
- name: Deploy Docker Compose on Application Server
  hosts: app
  become: yes
  vars_files:
    - docker_hub_credentials.yml
  vars:
    ansible_ssh_private_key_file: /root/Test.pem
    ansible_user: ec2-user
    docker_compose_file: /root/docker-compose-app.yml

  tasks:
    - name: Copy Docker Compose file for the application
      copy:
        src: /root/docker-compose-app.yml
        dest: "{{ docker_compose_file }}"
        owner: root
        group: root
    
    - name: Copy .env file
      copy:
        src: /root/.env
        dest: /root/.env
        owner: root
        group: root

    - name: Run Docker Compose for the application
      become: yes
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin/docker-compose-directory"
      command: /usr/local/bin/docker-compose -f "{{ docker_compose_file }}" up -d
