---
- name: Install Docker on EC2
  hosts: ec2
  become: yes
  tasks:
    - name: Update package cache
      package:
        name: "*"
        state: latest
      become: yes

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
          #   - name: Log in to Docker Hub
          #      shell: |
          #        docker login -u "{{ docker_hub_username }}" -p "{{ docker_hub_password }}"
